---
title: "FML Mass"
author: "Garrick Bruening"
output:
  bookdown::html_document2:
    toc: true
  bookdown::pdf_document2: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(ggthemes)
library(lmtest)
library(tidyr)
library(multcomp)
library(lme4)
library(nlstools)
library(knitr)
library("RColorBrewer")
library(wesanderson)
library(extrafont)
library(cowplot)
library(latex2exp)
library('R.matlab')
library(boot)
library(viridis)
library(dplyr)
library(moments)

#====================== Load Fonts
# font_import()
loadfonts(device='win')
windowsFonts(Times=windowsFont("TT Times New Roman"))
extrafont::loadfonts()

# theme_set(theme_cowplot(font_size=12,font_family = "Times"))
# theme_set(theme_gray(base_family = "Times"))
theme_set(theme_classic()+
            theme(text = element_text(color='black'),
                  axis.text.x = element_text(color='black'),
                  axis.text.y = element_text(color='black'),
                  axis.ticks  = element_line(color='black'),
                  axis.line = element_line(color='black',linetype='solid'),
                  plot.title = element_text(hjust = 0.5))+
  theme(axis.text         = element_text(color='black'),
        axis.ticks        = element_line(color='black'),
        legend.text       = element_text(size=15),
        legend.text.align = 0,
        legend.position   = 'right',
        plot.title        = element_text(hjust = 0.5),
        axis.line         = element_line(color='black')))
theme_set(theme_cowplot())

save_plots = 0

# #====================== LOAD DATA - Neuromech ==============================
# met_plots_dir  <- 'D:/Users/Gary/Google Drive/Muscle modeling/Metabolics/Graphs/'
# pref_plots_dir <- 'D:/Users/Gary/Google Drive/Preferred Mass/Graphs/'
# 
# prefdata   <- read.csv('D:/Users/Gary/Google Drive/Preferred Mass/2018Data-UnorderednoFML.csv')
# # prefdata   <- read.csv('D:/Users/Gary/Google Drive/Preferred Mass/FullData_noFML_test.csv')
# metdata    <- read.csv('D:/Users/Gary/Google Drive/Muscle modeling/Metabolics/Data/Met_data_erik_test.csv')$baseline
# mpdata     <- read.csv('D:/Users/Gary/Google Drive/Muscle modeling/Metabolics/Data/met_power_data.csv')
# mpdata_rest <- readMat('D:/Users/Gary/Google Drive/Muscle modeling/Metabolics/Data/baselinemetabolics.mat')

# pilotdata  <- read.csv('D:/Users/Gary/Google Drive/Preferred Mass/Pilot_Data-UnorderednoFML.csv')
# smalltdata <- read.csv('D:/Users/Gary/Google Drive/Preferred Mass/FullData_SmallTargetnoFML_test.csv')
# 
# eff_masses_pref <- read.csv('D:/Users/Gary/Google Drive/Preferred Mass/eff_masses.csv',header=0)
# eff_masses_meta <- read.csv('D:/Users/Gary/Google Drive/Muscle modeling/Metabolics/Data/eff_masses.csv',header=0)
# 
# react_sim <-read.csv('D:/Users/Gary/Google Drive/Muscle Modeling/Min_jerk_files/Data/react_sim.csv')
# resample_data_abs  = readMat('D:/Users/Gary/Google Drive/Preferred Mass/Data/Resample_data_abs2.mat')
# resample_data_perc = readMat('D:/Users/Gary/Google Drive/Preferred Mass/Data/Resample_data_perc.mat')
# torque2_data <- read.csv('D:/Users/Gary/Google Drive/Muscle modeling/Min_jerk_files/Data/sum_torque2_only.csv')
# torque2_mj_data <- read.csv('D:/Users/Gary/Google Drive/Muscle modeling/Min_jerk_files/Data/sum_torque2_scscript.csv')
# 
# # mpdata = subset(mpdata, metpowernet<max(mpdata$metpowernet)*.99)

# #====================== LOAD DATA - Desky ==============================
# met_plots_dir <- 'F:/Google Drive/Muscle modeling/Metabolics/Graphs/'
# pref_plots_dir <- 'F:/Google Drive/Preferred Mass/Graphs/'
# 
# prefdata <-read.csv('F:/Google Drive/Preferred Mass/2018Data-UnorderednoFML.csv')
# metdata<-read.csv('F:/Google Drive/Muscle modeling/Metabolics/Data/Met_data_erik_test.csv')
# mpdata <- read.csv('F:/Google Drive/Muscle modeling/Metabolics/Data/met_power_data.csv')
# mpdata_rest <- readMat('F:/Google Drive/Muscle modeling/Metabolics/Data/baselinemetabolics.mat')$baseline
# pilotdata <- read.csv('F:/Google Drive/Preferred Mass/Pilot_Data-UnorderednoFML.csv')
# smalltdata <- read.csv('F:/Google Drive/Preferred Mass/DataArcT-UnorderednoFML.csv')
# 
# eff_masses_pref <- read.csv('F:/Google Drive/Preferred Mass/eff_masses.csv',header=0)
# eff_masses_meta <- read.csv('F:/Google Drive/Muscle modeling/Metabolics/Data/eff_masses.csv',header=0)
# 
# react_sim <-read.csv('F:/Google Drive/Muscle Modeling/Min_jerk_files/Data/react_sim.csv')
# torque2_data <- read.csv('F:/Google Drive/Muscle modeling/Min_jerk_files/Data/sum_torque2_only.csv')
# torque2_mj_data <- read.csv('F:/Google Drive/Muscle modeling/Min_jerk_files/Data/sum_torque2_scscript.csv')
# 
# resample_data_pref_abs = readMat('F:/Google Drive/Preferred Mass/Data/Resample_data_abs2.mat')
# resample_data_pref_perc = readMat('F:/Google Drive/Preferred Mass/Data/Resample_data_perc.mat')
# resample_data_pilot_abs = readMat('F:/Google Drive/Preferred Mass/Data/Resample_data_pilot_abs.mat')
# resample_data_smallt_abs = readMat('F:/Google Drive/Preferred Mass/Data/Resample_data_smallt_abs.mat')

#====================== LOAD DATA ==============================
parent_directory = 'F:/Google Drive/Preferred Mass/alaa code'
setwd(parent_directory)
met_plots_dir <- paste(parent_directory,'/Graphs_met/',sep='')
pref_plots_dir <- paste(parent_directory,'/Graphs_pref/',sep='')

prefdata <-read.csv('2018Data-UnorderedwithFML.csv')
metdata<-read.csv('Met_data_erik_test.csv')
mpdata <- read.csv('met_power_data.csv')
mpdata_rest <- readMat('baselinemetabolics.mat')$baseline
pilotdata <- read.csv('Pilot_Data-UnorderedwithFML.csv')
smalltdata <- read.csv('DataArcT-UnorderedwithFML.csv')

eff_masses_pref <- read.csv('eff_masses_pref.csv',header=0)
eff_masses_meta <- read.csv('eff_masses_meta.csv',header=0)

react_sim <-read.csv('react_sim.csv')
torque2_data <- read.csv('sum_torque2_only.csv')
torque2_mj_data <- read.csv('sum_torque2_scscript.csv')

# resample_data_pref_abs = readMat('Resample_data_pref_abs_wait4mvt.mat')
# resample_data_pref_perc = readMat('Resample_data_perc.mat')
# resample_data_pilot_abs = readMat('Resample_data_pilot_abs_wait4mvt.mat')
# resample_data_smallt_abs = readMat('Resample_data_smallt_abs_wait4mvt.mat')

# resample_data_pref_abs = readMat('Resample_data_abs2.mat')
# resample_data_pref_perc = readMat('Resample_data_perc.mat')
# resample_data_pilot_abs = readMat('Resample_data_pilot_abs.mat')
# resample_data_smallt_abs = readMat('Resample_data_smallt_abs.mat')

# ===================== Add things =================================================
pilotdata$reacttoback <- (pilotdata$idxmoveback - pilotdata$idxonset)*.005
pilotdata$reaction_tanv <- .005*pilotdata$reaction_tanv
pilotdata$movedur <- pilotdata$reacttoback
pilotdata$peakvel_target <- pilotdata$peakvel_radv

prefdata$reaction_tanv <- .005*prefdata$reaction_tanv
smalltdata$reaction_tanv <- .005*smalltdata$reaction_tanv

prefdata$reaction_erik <- 0.005*(prefdata$idxonsetErik-prefdata$idxtargetshow)
prefdata$reaction_vthresh <- 0.005*(prefdata$vthres_onset-prefdata$idxtargetshow)
prefdata$reaction_extrap <- 0.005*(prefdata$idxonset_extrap-prefdata$idxtargetshow)

smalltdata$reaction_erik <- 0.005*(smalltdata$idxonsetErik-smalltdata$idxtargetshow)
smalltdata$reaction_vthresh <- 0.005*(smalltdata$vthres_onset-smalltdata$idxtargetshow)
smalltdata$reaction_extrap <- 0.005*(smalltdata$idxonset_extrap-smalltdata$idxtargetshow)

pilotdata$reaction_erik <- 0.005*(pilotdata$idxonsetErik-pilotdata$idxtargetshow)
pilotdata$reaction_vthresh <- 0.005*(pilotdata$vthres_onset-pilotdata$idxtargetshow)
pilotdata$reaction_extrap <- 0.005*(pilotdata$idxonset_extrap-pilotdata$idxtargetshow)

# ===================== Adding Eff_mass =======================
# Adding Column for estimated eff_mass to preferred experiment.
index <- c(0,3,5,8)
values <- c(2.47,3.80,4.7,6.1)
subjects = c(1,2,3,4,5,6,7,8,9,10,11,12)
prefdata$eff_mass <- values[match(prefdata$condition,index)]
pilotdata$eff_mass <- values[match(pilotdata$condition,index)]
smalltdata$eff_mass <- values[match(smalltdata$condition,index)]

eff_mass = numeric(length(prefdata$movedur))
for (i in 1:length(prefdata$movedur)){
    eff_mass[i] = eff_masses_pref[match(prefdata$condition[i],index),match(prefdata$subj[i],subjects)]
}

prefdata$eff_mass2 <- eff_mass

#============================ Filtering Funciton =========================
filtering_func <- function(vars,data,dataname){
  for (cond in c(0,3,5,8)){
    filt_string = ""
    for (var in vars){
      eval(parse(text = paste(var,cond,' = boxplot.stats(filter(',dataname,',condition == ',cond,')$',var,')$out', sep = "")))
      eval(parse(text = paste(var,cond,'_high = min(',var,cond,'[',var,cond,'>median(filter(data,condition==',cond,')$',var,')])', sep = "")))
      
      lowstring <- paste('if (length(',var,cond,'[',var,cond,'<mean(filter(data,condition==',cond,')$',var,')])>0){
                         ',var,cond,'_low = max(',var,cond,'[',var,cond,'<mean(filter(data,condition==',cond,')$',var,')])
    } else{
                         ',var,cond,'_low = 0
    }',sep="")
      eval(parse(text = lowstring))
      filt_string <- paste(filt_string,',',var,'<',var,cond,'_high,',var,'>',var,cond,'_low', sep = "")
  }
    eval(parse(text = paste('a',cond,' <- filter(data,condition == ',cond,filt_string,')', sep = "")))
}
  data <- rbind(a0,a3,a5,a8)
  return(data)
}

# ========================== Filtering ================================================
prefdata <- filtering_func(c('movedur','reaction_tanv','reaction_tanvel','miss_dist'),prefdata,'prefdata')
prefdata <- filter(prefdata,maxex<.14,odd_trial==1)

# pilotdata <- filter(pilotdata,reacttoback<3.0,reacttoback>.25,idxonset1<100)
pilotdata <- filter(pilotdata,trialtot>200)
pilotdata$miss_dist <- pilotdata$maxex
pilotdata <-filtering_func(c('movedur','reaction_tanv','reaction_tanvel','miss_dist'),pilotdata,'pilotdata')
pilotdata <- filter(pilotdata,maxex<.20)

smalltdata <- filtering_func(c('movedur','reaction_tanv','reaction_tanvel'),smalltdata,'smalltdata')
# smalltdata <- filter(pilotdata,max)

prefdata_factor <- prefdata
prefdata_factor$eff_mass <- as.factor(prefdata_factor$eff_mass)
prefdata_factor$condition <- as.factor(prefdata_factor$condition)
prefdata_factor$targetnum <- as.factor(prefdata_factor$targetnum)

smalltdata_factor <- smalltdata
smalltdata_factor$eff_mass <- as.factor(smalltdata_factor$eff_mass)
smalltdata_factor$condition <- as.factor(smalltdata_factor$condition)
smalltdata_factor$targetnum <- as.factor(smalltdata_factor$targetnum)

pilotdata_factor <- pilotdata
pilotdata_factor$eff_mass <- as.factor(pilotdata_factor$eff_mass)
pilotdata_factor$condition <- as.factor(pilotdata_factor$condition)
pilotdata_factor$targetnum <- as.factor(pilotdata_factor$targetnum)

met_orig_length = length(metdata$movedur)

metdata = filter(metdata,odd_trial==1)
met_length = length(metdata$movedur)
metdata <- filter(metdata,miss_dist<.1,movedur>.2,movedur<2,maxex<.2,reaction_tanv<.5,abs(missangle)<50)

index <- c(1,2,3,4)
values <- c(2.47,4.730,6.990,11.50)
metdata$eff_mass <- values[match(metdata$condition,index)]
metdata = cbind(metdata,metdata$trial%%2==0)
colnames(metdata) = append(colnames(metdata)[1:length(colnames(metdata))-1],'outward')
#metdata2 = metdata
metdata = filter(metdata,odd_trial==1)


# ========================== Adding Metabolics things =========================================

index <- c(2.47,4.730,6.990,11.50)
values <- c(1,2,3,4)
mpdata$condition <- values[match(mpdata$effmass,index)]

# Adding Column for estimated eff_mass to preferred experiment.
index <- c(1,2,3,4)
values <- c(2.47,4.730,6.990,11.50)
subjects = c(1,2,3,4,5,6,7,8)

eff_mass = numeric(length(metdata$subj))
for (i in 1:length(metdata$subj)){
    eff_mass[i] = eff_masses_meta[match(metdata$condition[i],index),match(metdata$subj[i],subjects)]
}

metdata$eff_mass2 <- eff_mass
metdata$effmass = metdata$eff_mass

index <- c(2.47,4.730,6.990,11.50)
eff_mass = numeric(length(mpdata$subj))
for (i in 1:length(mpdata$subject)){
  eff_mass[i] = eff_masses_meta[match(mpdata$effmass[i],index),match(mpdata$subj[i],subjects)]
  # mpdata$metpowergross[i] = mpdata$metpowernet[i]+mpdata_rest[mpdata$subject[i],mpdata$condition[i]]
  mpdata$metpowerrest[i] = mpdata_rest[mpdata$subject[i],mpdata$condition[i]]
}

mpdata$effmass2 <- eff_mass


# ========================== Adding Variance Metrics =========================================

stdev_trial_plot <- function(data, variable, add_or_plot){
  if (add_or_plot=='add'){
    max_trial = max(data$trial)
    
    for (k in 11:(length(data$subj)-10)){
      if (var(data[(k-10):(k+10),'eff_mass'])==0){
        if ('speed' %in% colnames(data) && var(data[(k-10):(k+10),'speed'])==0){
          data[k,paste(variable,'_sd',sep='')] = sd(data[(k-10):(k+10),variable])
        } else {
          data[k,paste(variable,'_sd',sep='')] = sd(data[(k-10):(k+10),variable])
        }
      } else {
        data[k,paste(variable,'_sd',sep='')] = NaN
      }
    }
    
    return(data)
  }
  if (add_or_plot=='plot'){
    eval(parse(text = paste('data$yvar = data$',variable,'_sd',sep='')))
    g<-ggplot(data=data)+
      geom_smooth(aes(x=trial,
                      y=yvar,
                      color = factor(subj)))+
      theme_classic()+
      labs(x = 'Trial Number', y = paste('StDev (',variable,')',sep=''),color = 'Subject')
    
    if ('speed' %in% colnames(data)){
      g<-g+facet_grid(rows = vars(eff_mass),cols = vars(speed))
    } else {
      g<-g+facet_grid(rows = vars(eff_mass))
    }
    return(g)
  }
}

average_trial_plot <- function(data, variable, add_or_plot){
  if (add_or_plot=='add'){
    max_trial = max(data$trial)
    
    for (k in 11:(length(data$subj)-10)){
      if (var(data[(k-10):(k+10),'eff_mass'])==0){
        if ('speed' %in% colnames(data) && var(data[(k-10):(k+10),'speed'])==0){
          data[k,paste(variable,'_avg',sep='')] = mean(data[(k-10):(k+10),variable])
        } else {
          data[k,paste(variable,'_avg',sep='')] = mean(data[(k-10):(k+10),variable])
        }
      } else {
        data[k,paste(variable,'_avg',sep='')] = NaN
      }
    }
    
    return(data)
  }
  if (add_or_plot=='plot'){
    eval(parse(text = paste('data$yvar = data$',variable,'_avg',sep='')))
    g<-ggplot(data=data)+
      geom_smooth(aes(x=trial,
                      y=yvar,
                      color = factor(subj)))+
      theme_classic()+
      labs(x = 'Trial Number', y = paste('Average (',variable,')',sep=''),color = 'Subject')
    
    if ('speed' %in% colnames(data)){
      g<-g+facet_grid(rows = vars(eff_mass),cols = vars(speed))
    } else {
      g<-g+facet_grid(rows = vars(eff_mass))
    }
    return(g)
  }
}


for (variable in c('miss_dist','miss_rad','missangle')){
  prefdata <- stdev_trial_plot(prefdata,variable,'add')
  smalltdata <- stdev_trial_plot(smalltdata,variable,'add')
  pilotdata <- stdev_trial_plot(pilotdata,variable,'add')
  metdata <- stdev_trial_plot(metdata,variable,'add')
  
  prefdata <- average_trial_plot(prefdata,variable,'add')
  smalltdata <- average_trial_plot(smalltdata,variable,'add')
  pilotdata <- average_trial_plot(pilotdata,variable,'add')
  metdata <- average_trial_plot(metdata,variable,'add')
}


# =========================== Generate the df for 3 experiments ===================
prefdata$exp <- 'pref'
pilotdata$exp <- 'pilot'
smalltdata$exp <- 'smallt'
smalltdata$subj <- smalltdata$subj+12
pilotdata$subj <- pilotdata$subj+12+12

allexp_plot <- function(vars,data,...){
  str = paste('a=as.data.frame(cbind(',data,'$subj,',data,'$eff_mass,',data,'$condition,',data,'$exp',sep='')
  for (var in vars){
    # print(var)
    str = paste(str,',',data,'$',var,sep='')
  }
  str = paste(str,'))',sep='')
  a= eval(parse(text=str))
  colnames(a) = c('subj','eff_mass','condition','exp',vars)
  a$eff_mass = as.numeric(as.character(a$eff_mass))
  a$condition = as.numeric(as.character(a$condition))
  for (var in vars){
    eval(parse(text = paste('a$',var,' = as.numeric(as.character(a$',var,'))',sep='')))
  }
  return(a)
}

vars = c('targetnum','movedur','peakvel_target','miss_dist','reaction_tanv','reaction_tanvel',
         'pathltar','missangle','miss_rad','trial',
         'miss_dist_avg','miss_dist_sd',
         'missangle_avg','missangle_sd',
         'miss_rad_avg','miss_rad_sd')
a=allexp_plot(vars,'prefdata')
b=allexp_plot(vars,'pilotdata')
c=allexp_plot(vars,'smalltdata')

b$peakvel_target = pilotdata$peakvel_radv
# colnames(b)[colnames(b)=='peakvel_target'] <- 'peavel_radv'

prefpilot=data.frame(rbind(a,b,c))
prefpilot = filter(prefpilot,movedur<1.75)
prefpilot$subj <- as.numeric(prefpilot$subj)

# a=as.data.frame(cbind(pilotdata$subj,pilotdata$eff_mass,pilotdata$exp,pilotdata$targetnum,pilotdata$reacttoback,pilotdata$reaction_tanv,pilotdata$miss_rad,pilotdata$peakvel_target))
# b=as.data.frame(cbind(prefdata$subj,prefdata$eff_mass,prefdata$exp,prefdata$targetnum,prefdata$movedur,prefdata$reaction_tanv,prefdata$miss_rad,prefdata$peakvel_target))
# c=as.data.frame(cbind(smalltdata$subj,smalltdata$eff_mass,smalltdata$exp,smalltdata$targetnum,smalltdata$movedur,smalltdata$reaction_tanv,smalltdata$miss_rad,smalltdata$peakvel_target))
# prefpilot=data.frame(rbind(a,b,c))
# colnames(prefpilot) = cbind('subj','eff_mass','exp','targetnum','movedur','reaction_tanv','miss_rad','peakvel_target')
# prefpilot$movedur<-as.numeric(as.character(prefpilot$movedur))
# prefpilot$eff_mass<-as.numeric(as.character(prefpilot$eff_mass))
# prefpilot$reaction_tanv<-as.numeric(as.character(prefpilot$reaction_tanv))
# prefpilot$miss_rad<-as.numeric(as.character(prefpilot$miss_rad)) 
# prefpilot$peakvel_target<-as.numeric(as.character(prefpilot$peakvel_target))
# prefpilot=filter(prefpilot,movedur<1.5,movedur>.25,reaction_tanv<.5,miss_rad>.08,miss_rad<.2)

# ===================== Setting plots sizes ===================
# Pref stuff
vplot_point_size = 0
vplot_avg_point_size = 3
v_plot_line_size = 1
v_plot_err_bar_size = 1

vel_plot_line_size = 1
vel_plot_point_size = 3

err_plot_point_size = 1
err_plot_line_size = 1

react_plot_point_size = 1

# Met stuff
met_point_size = 3
met_costmin_size = met_point_size-2
met_line_size = .5

met_errorbar_size = 1

# ===================== Fucntions ===================
# Violin Plotting Function
vplot <- function(variable,data,...){
  exp = list(...)
  string = paste('a = aggregate(',variable,' ~ subj + eff_mass,data,mean)
                  b = aggregate(',variable,' ~ subj + eff_mass,data,sd)
                  c = cbind(a,b$',variable,')
                  colnames(c) = c(\'subj\',\'eff_mass\',\'dep_var\',\'dep_var_sd\')
                  
                  d = aggregate(',variable,' ~ eff_mass,data,mean)
                  e = aggregate(',variable,' ~ eff_mass,a,sd)
                  e = cbind(e$eff_mass,d$',variable,',e$',variable,')
                  colnames(e) = c(\'eff_mass\',\'dep_var_avg\',\'dep_var_sd\')'
                 )
  eval(parse(text=string))
  
  string = paste('g<-ggplot()+
                     geom_violin(data=data,aes(x=eff_mass,y=',variable,',fill = factor(eff_mass)))',sep='')
  eval(parse(text = string))
  g<-g+
    scale_x_continuous(breaks=c(sort(unique(c$eff_mass))))+
    scale_fill_manual(values=mass_colors)+
    geom_point(data=data.frame(c),
              aes(x=eff_mass,
                  y=dep_var),
              size=vplot_point_size)+
    geom_line(data=data.frame(e),
             aes(eff_mass,
                 y=dep_var_avg),
             size=v_plot_line_size)+
    geom_point(data=data.frame(e),
              aes(eff_mass,
                  y=dep_var_avg),
              size=vplot_avg_point_size)+
    geom_errorbar(data=data.frame(e),
                 aes(x    = eff_mass,
                     y    = dep_var_avg, 
                     ymin = dep_var_avg-dep_var_sd,
                     ymax = dep_var_avg+dep_var_sd),
                 size=v_plot_err_bar_size,
                 width = 0) +
    theme(text              = element_text(color='black'),
         axis.text         = element_text(color='black'),
         axis.ticks        = element_line(color='black'),
         plot.title        = element_text(hjust = 0.5),
         axis.line         = element_line(color='black'))+
    labs(x = 'Effective Mass (kg)', color = 'Effective\nMass (kg)', fill = 'Effective\nMass (kg)')+
    geom_hline(yintercept=e[1,2],linetype='dashed',size=.5)
    
  
  # string = paste('ggplot()+
  #                    geom_violin(data=data,aes(x=eff_mass,y=',variable,',fill = factor(eff_mass)))+
  #                    scale_x_continuous(breaks=c(sort(unique(data$eff_mass))))+
  #                    scale_fill_manual(values=mass_colors)+
  #                    geom_point(data=aggregate(',variable,'~subj+eff_mass,data,mean),aes(x=eff_mass,y=',variable,'),size=vplot_point_size)+
  #                    # geom_line(data=c,aes(x=eff_mass,y=dep_var,group=factor(subj)))+
  #                    geom_line(data=aggregate(',variable,'~eff_mass,data,mean),aes(eff_mass,y=',variable,'),size=v_plot_line_size)+
  #                    geom_point(data=aggregate(',variable,'~eff_mass,data,mean),aes(eff_mass,y=',variable,'),size=vplot_avg_point_size)+
  #                    geom_errorbar(data=data.frame(e),aes(x= eff_mass,
  #                                                         y=movedur_avg, 
  #                                                         ymin = movedur_avg-movedur_sd,
  #                                                         ymax=movedur_avg+movedur_sd),
  #                                                     size=v_plot_err_bar_size,
  #                                                     width = 0) +
  #                    theme(text              = element_text(color=\'black\'),
  #                          axis.text         = element_text(color=\'black\'),
  #                          axis.ticks        = element_line(color=\'black\'),
  #                          plot.title        = element_text(hjust = 0.5),
  #                          axis.line         = element_line(color=\'black\'))+
  #                    labs(title=\'',exp,'\')+
  #                    labs(x = \'Effective Mass (kg)\', color = \'Effective\nMass (kg)\')',sep='')
  # eval(parse(text = string))
  
  return(g)
}

avg_plot <- function(variable,data,ylab,shape=21,...){
  exp = list(...)
  tempdf = eval(parse(text = paste('aggregate(',variable,' ~ subj + eff_mass,data,mean)',sep='')))
  nsubj = max(tempdf$subj)
  string = paste('a = aggregate(',variable,' ~ eff_mass,tempdf,mean)
                  b = aggregate(',variable,' ~ eff_mass,tempdf,sd)
                  c = cbind(a,b$',variable,'/sqrt(nsubj))
                  colnames(c) = c(\'eff_mass\',\'dep_var\',\'dep_var_sd\')',
                 sep = ''
                 )
  eval(parse(text=string))
  
  g<-ggplot()+
    scale_x_continuous(breaks=c(sort(unique(data$eff_mass))))+
    geom_line(data=c,
              aes(x=eff_mass,
                  y=dep_var),
              size=v_plot_line_size)+
    geom_hline(data = c,aes(yintercept = c[1,2]),
               linetype = 'dashed',
               size=.5)+
    geom_errorbar(data=data.frame(c),
                  aes(x    = eff_mass,
                      y    = dep_var, 
                      ymin = dep_var-dep_var_sd,
                      ymax = dep_var+dep_var_sd),
                  size=v_plot_err_bar_size,
                  width = 0)+
    geom_point(data=c,
               aes(x=eff_mass,
                   y=dep_var,
                   fill = factor(eff_mass)),
               color = 'black',
               shape = shape,
               size=vplot_point_size+4)+
    scale_fill_manual(values=mass_colors)+
    theme_classic()+
    theme(text              = element_text(color='black'),
         axis.text         = element_text(color ='black'),
         axis.ticks        = element_line(color ='black'),
         plot.title        = element_text(hjust = 0.5),
         axis.line         = element_line(color ='black'))+
    labs(x = 'Effective Mass (kg)', fill = 'Effective\nMass (kg)')
  if (!missing(ylab)){
    g <- g+labs(y = ylab)
  }
  return(g)
}
#theme(axis.line = element_line(color=\'black\',size = 2,linetype=\'solid\'))+

avg_plot2 <- function(variable,data,ylab,shape_labs,...){
  exp = list(...)
  if (length(variable)>1){
    var_count = 1
    var1 = variable[1]
    tempdf = eval(parse(text = paste('aggregate(',var1,' ~ subj + eff_mass,data,mean)',sep='')))
    nsubj = max(tempdf$subj)
    
    string = paste('a = aggregate(',var1,' ~ eff_mass,tempdf,mean)
                    b = aggregate(',var1,' ~ eff_mass,tempdf,sd)
                    c = cbind(a,b$',var1,'/sqrt(nsubj),rep(var_count,4))
                    colnames(c) = c(\'eff_mass\',\'dep_var\',\'dep_var_se\',\'var_num\')',
                   sep = ''
                   )
    eval(parse(text=string))
    
    var_count = 2
    for (var1 in variable[2:length(variable)]){
      tempdf = eval(parse(text = paste('aggregate(',var1,' ~ subj + eff_mass,data,mean)',sep='')))
      nsubj = max(tempdf$subj)
      
      string = paste('a = aggregate(',var1,' ~ eff_mass,tempdf,mean) %>% `colnames<-`(c(\'eff_mass\',\'dep_var\'))
                    b = aggregate(',var1,' ~ eff_mass,tempdf,sd) %>% `colnames<-`(c(\'eff_mass\',\'dep_var_sd\'))')
      eval(parse(text = string))
      string = paste('c = rbind(c,cbind(a, b$dep_var_sd/sqrt(nsubj), rep(var_count,4)) %>% `colnames<-`(c(\'eff_mass\',\'dep_var\',\'dep_var_se\',\'var_num\')))')
      eval(parse(text = string))
      
      var_count = var_count + 1
    }
  } else {
    tempdf = eval(parse(text = paste('aggregate(',var1,' ~ subj + eff_mass,data,mean)',sep='')))
    nsubj = max(tempdf$subj)
    
    string = paste('a = aggregate(',variable,' ~ eff_mass,tempdf,mean)
                    b = aggregate(',variable,' ~ eff_mass,tempdf,sd)
                    c = cbind(a,b$',variable,'/sqrt(nsubj))
                    colnames(c) = c(\'eff_mass\',\'dep_var',1,'\',\'dep_var_se',1,'\')',
                   sep = ''
                   )
    eval(parse(text=string))
  }
  
  g<-ggplot()+
    scale_x_continuous(breaks=c(sort(unique(data$eff_mass))))
    
  for (var_count in 1:length(variable)){
    g <- g+geom_line(data=filter(c,var_count==var_num),
              aes(x=eff_mass,
                  y=dep_var),
              size=v_plot_line_size)
  }
    g<-g+geom_hline(data = c,
               aes(yintercept = c[1,2]),
               linetype = 'dashed',
               size=.5)+
    geom_errorbar(data=data.frame(c),
                  aes(x    = eff_mass,
                      y    = dep_var, 
                      ymin = dep_var-dep_var_se,
                      ymax = dep_var+dep_var_se),
                  size=v_plot_err_bar_size,
                  width = 0)+
    geom_point(data=c,
               aes(x=eff_mass,
                   y=dep_var,
                   color = 'black',
                   shape = factor(var_num)),
               size=vplot_point_size+7.5)+
    geom_point(data=c,
               aes(x=eff_mass,
                   y=dep_var,
                   color = factor(eff_mass),
                   shape = factor(var_num)),
               size=vplot_point_size+6)+
    scale_color_manual(values=c(mass_colors,'black'))+
    theme_classic()+
    theme(text              = element_text(color='black'),
         axis.text         = element_text(color ='black'),
         axis.ticks        = element_line(color ='black'),
         plot.title        = element_text(hjust = 0.5),
         axis.line         = element_line(color ='black'))+
    labs(x = 'Effective Mass (kg)', color = 'Effective\nMass (kg)')
  if (!missing(ylab)){
    g <- g+labs(y = ylab)
  }
  if (!missing(shape_labs)){
    g <- g+scale_shape_manual(values = c(16,17,15,18),labels = shape_labs)+labs(shape = 'Algorithm')
  }
  return(g)
}

all_exp_avg_plot <- function(variable,data1,data2,data3,ylab,...){
  exp = list(...)
  c = c()
  
  exps = c('2a','2b','2c')
  tempdf = list()
  for (datasets in c(1,2,3)){
    tempdf[[datasets]] = eval(parse(text = paste('aggregate(',variable,' ~ subj + eff_mass,data',datasets,',mean)',sep='')))
    nsubj = max(tempdf[[datasets]]$subj)
    string = paste('a = aggregate(',variable,' ~ eff_mass,tempdf[[datasets]],mean)
                    b = aggregate(',variable,' ~ eff_mass,tempdf[[datasets]],sd)
                    tempdf[[datasets]] = cbind(a,b$',variable,'/sqrt(nsubj))
                    colnames(tempdf[[datasets]]) = c(\'eff_mass\',\'dep_var\',\'dep_var_sd\')',
                   sep = ''
                   )
    eval(parse(text=string))
    tempdf[[datasets]]$exp = exps[datasets]
  }
  c = rbind(tempdf[[1]],tempdf[[2]],tempdf[[3]])
                
  g<-ggplot()+
    scale_x_continuous(breaks=c(sort(unique(c$eff_mass))))+
    geom_line(data=c,
              aes(x = eff_mass,
                  y = dep_var,
                  group = exp),
              size=v_plot_line_size)+
    geom_hline(aes(yintercept = filter(c,exp=='2a')[1,2]),
               linetype = 'dashed',
               size=.5)+
    geom_hline(aes(yintercept = filter(c,exp=='2b')[1,2]),
               linetype = 'dashed',
               size=.5)+
    geom_hline(aes(yintercept = filter(c,exp=='2c')[1,2]),
               linetype = 'dashed',
               size=.5)+
    geom_errorbar(data=data.frame(c),
                  aes(x    = eff_mass,
                      y    = dep_var, 
                      ymin = dep_var-dep_var_sd,
                      ymax = dep_var+dep_var_sd),
                  size=v_plot_err_bar_size,
                  width = 0)+
    geom_point(data=c,
               aes(x=eff_mass,
                   y=dep_var,
                   fill = factor(eff_mass),
                   shape = factor(exp)),
               size=vplot_point_size+6,
               color = 'black')+
    scale_fill_manual(values=c(mass_colors,'black'))+
    scale_shape_manual(values=c(21,22,24))+
    theme_classic()+
    theme(text              = element_text(color='black'),
          axis.text         = element_text(color ='black'),
          axis.ticks        = element_line(color ='black'),
          plot.title        = element_text(hjust = 0.5),
          axis.line         = element_line(color ='black'))+
    labs(x = 'Effective Mass (kg)',
         shape = 'Experiment')+
    guides(fill='none')
  if (!missing(ylab)){
    g <- g+labs(y = ylab)
  }
  return(g)
}
#theme(axis.line = element_line(color=\'black\',size = 2,linetype=\'solid\'))+

#Another stat summary function
summarySE <- function(data=NULL, measurevar, groupvars=NULL, na.rm=FALSE,
                      conf.interval=.95, .drop=TRUE) {
    library(plyr)

    # New version of length which can handle NA's: if na.rm==T, don't count them
    length2 <- function (x, na.rm=FALSE) {
        if (na.rm) sum(!is.na(x))
        else       length(x)
    }

    # This does the summary. For each group's data frame, return a vector with
    # N, mean, and sd
    datac <- ddply(data, groupvars, .drop=.drop,
      .fun = function(xx, col) {
        c(N    = length2(xx[[col]], na.rm=na.rm),
          mean = mean   (xx[[col]], na.rm=na.rm),
          sd   = sd     (xx[[col]], na.rm=na.rm)
        )
      },
      measurevar
    )

    # Rename the "mean" column    
    datac <- rename(datac, c("mean" = measurevar))

    datac$se <- datac$sd / sqrt(datac$N)  # Calculate standard error of the mean

    # Confidence interval multiplier for standard error
    # Calculate t-statistic for confidence interval: 
    # e.g., if conf.interval is .95, use .975 (above/below), and use df=N-1
    ciMult <- qt(conf.interval/2 + .5, datac$N-1)
    datac$ci <- datac$se * ciMult

    return(datac)
}

# Function to plot a variable by target
bytarget_plot <- function(var, data){
  data$condition = as.factor(data$condition)
  data <- summarySE(data, measurevar=var, groupvars=c("targetnum","condition"))
  bytarget_plot<-ggplot(data,
            aes(x=targetnum,
                y=movedur,
                color= condition,
                group = condition))+
    geom_errorbar(aes(ymin=movedur-se,
                      ymax=movedur+se),
                  width=.2,
                  size = 1)+
    geom_line(size = 1)+
    geom_point(size = 4)+
    scale_color_manual(values = mass_colors)
  return(bytarget_plot)
}

# Function to produce summary statistics (mean and +/- sd)
data_summary <- function(x) {
   m <- mean(x)
   ymin <- m-sd(x)
   ymax <- m+sd(x)
   return(c(y=m,ymin=ymin,ymax=ymax))
}


#Fischer Method Function
p_fisch_func <- function(var,data){
  p_fisch = c()
  chi_fisch = 0
  for (subjnum in unique(data$subj)){
    str = paste('p_fisch[subjnum] = anova(lm(',var,'~ targetnum + eff_mass2 + targetnum*eff_mass2,
             data=filter(data,subj == subjnum)))$`Pr(>F)`[2]',sep='')
    eval(parse(text = str))
    chi_fisch = chi_fisch + log(p_fisch[subjnum])
  }
  chi_fisch = -2*chi_fisch
  return(pchisq(chi_fisch, df=subjnum*2, lower.tail=FALSE))
}

gg_color_hue <- function(n) {
  hues = seq(15, 375, length = n + 1)
  hcl(h = hues, l = 65, c = 100)[1:n]
}

number_ticks <- function(n) {function(limits) pretty(limits, n)}

plots_to_fix = c('MPGross',
                 'MCGross',
                 'miss_dist_grouped_met',
                 'miss_anglevar_grouped_met',
                 'radial_endpointvar_grouped_met',
                 'reaction_bydur_met')
fix_plot_theme <- function(plot_to_fix,font){
    string = paste(plot_to_fix,'<-',plot_to_fix,'+
                   theme_classic()+
                   theme(text              = element_text(family=',font,',color=\'black\'),
                   axis.text         = element_text(color=\'black\'),
                   axis.ticks        = element_line(color=\'black\'),
                   plot.title        = element_text(hjust = 0.5),
                   axis.line         = element_line(color=\'black\'),
                   legend.position   = \'none\')',sep = '')
    eval(parse(text = string))
    return(plot_to_fix)
}

mass_exp_int_stringgen <- function(dataset, test_var, label){
  dataset$test_var = dataset[[test_var]]
  if ('targetnum' %in% colnames(dataset)){
    mass_exp_int_test = cftest(lmer(test_var ~ factor(targetnum) + eff_mass*factor(exp) +  (1|subj),data=dataset))
  } else {
    mass_exp_int_test = cftest(lmer(test_var ~ eff_mass*factor(exp) +  (1|subj),data=dataset))
  }
  
  if (mass_exp_int_test$test$pvalues[['eff_mass']] < 0.05){
    main_mass = paste('There is an overall effect of mass on ',label,' (slope = ',
                      formatC(mass_exp_int_test$coef[['eff_mass']],format = 'e',digits = 3),
                      ', p = ', formatC(mass_exp_int_test$test$pvalues[['eff_mass']],format = 'e',digits = 3),').', sep = '')
  } else {
    main_mass = paste('There is NOT an overall effect of mass on ',label,' (p = ',
                      formatC(mass_exp_int_test$test$pvalues[['eff_mass']],format = 'e',digits = 3),').',
                      sep = '')
  }
  
  # Main effects
  
  # 2b
  if (mass_exp_int_test$test$pvalues[['factor(exp)smallt']] < 0.05){
    if (mass_exp_int_test$coef[['factor(exp)smallt']] > 0){
      main_2b = paste('Experiment 2b ',label,' is significantly greater than 2a (slope = ',
                        formatC(mass_exp_int_test$coef[['factor(exp)smallt']],format = 'e',digits = 3),
                        ', p = ', formatC(mass_exp_int_test$test$pvalues[['factor(exp)smallt']],format = 'e',digits = 3),').', sep = '')
    } else {
      main_2b = paste('Experiment 2b ',label,' is significantly lower than 2a (slope = ',
                        formatC(mass_exp_int_test$coef[['factor(exp)smallt']],format = 'e',digits = 3),
                        ', p = ', formatC(mass_exp_int_test$test$pvalues[['factor(exp)smallt']],format = 'e',digits = 3),').', sep = '')
    }
  } else {
    main_2b = paste('Experiment 2b ',label,' is not different from 2a (p = ',
                    formatC(mass_exp_int_test$test$pvalues[['factor(exp)smallt']],format = 'e',digits = 3),').',
                    sep='')
  }
  
  # 2c
  if (mass_exp_int_test$test$pvalues[['factor(exp)pilot']] < 0.05){
    if (mass_exp_int_test$coef[['factor(exp)pilot']] > 0){
      main_2c = paste('Experiment 2c ',label,' is significantly greater than 2a (slope = ',
                        formatC(mass_exp_int_test$coef[['factor(exp)pilot']],format = 'e',digits = 3),
                        ', p = ', formatC(mass_exp_int_test$test$pvalues[['factor(exp)pilot']],format = 'e',digits = 3),').', sep = '')
    } else {
      main_2c = paste('Experiment 2c ',label,' is significantly lower than 2a (slope = ',
                        formatC(mass_exp_int_test$coef[['factor(exp)pilot']],format = 'e',digits = 3),
                        ', p = ', formatC(mass_exp_int_test$test$pvalues[['factor(exp)pilot']],format = 'e',digits = 3),').', sep = '')
    } 
  } else {
    main_2c = paste('Experiment 2c ',label,' is not different from 2a (p = ',
                    formatC(mass_exp_int_test$test$pvalues[['factor(exp)pilot']],format = 'e',digits = 3),').',
                    sep='')
  }
  
  # Interaction Effects
  
  # 2b
  if (mass_exp_int_test$test$pvalues[['factor(exp)pilot']] < 0.05){
    if (mass_exp_int_test$coef[['eff_mass:factor(exp)smallt']] > 0){
      mass_exp_in_2b = paste('Experiment 2b ',label,' increases with mass more than experiment 2a (slope = ',
                        formatC(mass_exp_int_test$coef[['eff_mass:factor(exp)smallt']],format = 'e',digits = 3),
                        ', p = ', formatC(mass_exp_int_test$test$pvalues[['eff_mass:factor(exp)smallt']],format = 'e',digits = 3),').', sep = '')
    } else {
      mass_exp_in_2b = paste('Experiment 2b ',label,' decreases with mass more than experiment 2a (slope = ',
                        formatC(mass_exp_int_test$coef[['eff_mass:factor(exp)smallt']],format = 'e',digits = 3),
                        ', p = ', formatC(mass_exp_int_test$test$pvalues[['eff_mass:factor(exp)smallt']],format = 'e',digits = 3),').', sep = '')
    }
  } else {
    mass_exp_in_2b = paste('Experiment 2b ',label,' did NOT change with mass more than 2a. (p = ',
                           formatC(mass_exp_int_test$test$pvalues[['eff_mass:factor(exp)smallt']],format = 'e',digits = 3),').',
                           sep='')
  }
  
  #2c
  if (mass_exp_int_test$test$pvalues[['eff_mass:factor(exp)pilot']] < 0.05){
    if (mass_exp_int_test$coef[['eff_mass:factor(exp)pilot']] > 0 ){
      mass_exp_in_2c = paste('Experiment 2c ',label,' increases with mass more than experiment 2a (slope = ',
                        formatC(mass_exp_int_test$coef[['eff_mass:factor(exp)pilot']],format = 'e',digits = 3),
                        ', p = ', formatC(mass_exp_int_test$test$pvalues[['eff_mass:factor(exp)pilot']],format = 'e',digits = 3),').', sep = '')
    } else {
      mass_exp_in_2c = paste('Experiment 2c ',label,' decreases with mass more than experiment 2a (slope = ',
                        formatC(mass_exp_int_test$coef[['eff_mass:factor(exp)pilot']],format = 'e',digits = 3),
                        ', p = ', formatC(mass_exp_int_test$test$pvalues[['eff_mass:factor(exp)pilot']],format = 'e',digits = 3),').', sep = '')
    }
  } else {
    mass_exp_in_2c = paste('Experiment 2c ',label,' did NOT change with mass more than 2a. (p = ',
                    formatC(mass_exp_int_test$test$pvalues[['eff_mass:factor(exp)pilot']],format = 'e',digits = 3),').',
                    sep='')
  }
  
  combined_string = paste(main_mass,'\n',
                          main_2b,'\n',
                          main_2c,'\n','\n',
                          'The interesting thing with these are the interaction effects.','\n',
                          mass_exp_in_2b,'\n',
                          mass_exp_in_2c,'\n',
                          sep='\n')
  return(combined_string)
}

table_func <- function(data, variable){
  eval(parse(text = paste('data$table_var = data$',variable,sep='')))
  tab = matrix(,nrow=4,ncol=7)
  for (s in c(1:7)){
    m_count = 0
    for (mass in c(2.47, 4.73, 6.99, 11.5)){
      m_count = m_count + 1
      avg = round(mean(filter(data,speed == s, effmass == mass)$table_var),4)
      se = round(sd(filter(data,speed == s, effmass == mass)$table_var)/sqrt(length(filter(data,speed == s, effmass == mass)$table_var)),4)
      tab[m_count,s] = paste(avg,"±",se,sep=' ')
    }
  }
  colnames(tab) = c('Speed = 1','Speed = 2','Speed = 3','Speed = 4','Speed = 5','Speed = 6','Speed = 7')
  rownames(tab) = c('2.73 kg','4.73 kg','6.99 kg','11.50 kg')
  return(tab)
}

table_func_nosd <- function(data, variable){
  eval(parse(text = paste('data$table_var = data$',variable,sep='')))
  tab = matrix(,nrow=4,ncol=7)
  for (s in c(1:7)){
    m_count = 0
    for (mass in c(2.47, 4.73, 6.99, 11.5)){
      m_count = m_count + 1
      avg = round(mean(filter(data,speed == s, effmass == mass)$table_var, na.rm = TRUE),4)
      tab[m_count,s] = paste(avg,sep=' ')
    }
  }
  colnames(tab) = c('Speed = 1','Speed = 2','Speed = 3','Speed = 4','Speed = 5','Speed = 6','Speed = 7')
  rownames(tab) = c('2.73 kg','4.73 kg','6.99 kg','11.50 kg')
  return(tab)
}


color1 = c(255,255,0)/255
color2 = c(255,196,0)/255
color3 = c(216,117,1)/255
color4 = c(139,0,0)/255

mass_colors <- c(rgb(color1[1],color1[2],color1[3]),
              rgb(color2[1],color2[2],color2[3]),
              rgb(color3[1],color3[2],color3[3]),
              rgb(color4[1],color4[2],color4[3]))



```

```{r, echo = FALSE, message = FALSE, warning = FALSE}

tab = matrix(,nrow=4,ncol=1)
dcount = 0
for (data in c('pref')){#,'smallt','pilot')){
  dcount = dcount +1
  eval(parse(text = paste('data_set = ',data,'data',sep='')))
  ccount = 0
  for (c in c(0,3,5,8)){
  ccount = ccount + 1
    tab[ccount,dcount] = paste(mean(filter(data_set,condition == c)$eff_mass2),
                               '±',
                               sd(filter(data_set,condition == c)$eff_mass2)/sqrt(12))
  }
}


```

```{r, echo = FALSE, message = FALSE, warning = FALSE}

temp_pref <- prefdata %>% group_by(subj,eff_mass) %>% summarise_each(funs(mean))

```

```{r}


prefdata[prefdata$trialtot<401,'condition'] = 'fml'
smalltdata[smalltdata$trialtot<401,'condition'] = 'fml'
pilotdata = filter(pilotdata, subj != 39)
pilotdata[pilotdata$trialtot<301,'condition'] = 'fml'


```

# Movement Duration

## Split by subj

```{r}
ggplot()+geom_smooth(data=prefdata,
                     aes(x = trial,
                         y = movedur,
                         color = factor(subj)))+
    facet_wrap(~factor(condition))+
  labs(title = 'Preferred')


ggplot()+geom_smooth(data=smalltdata,
                     aes(x = trial,
                         y = movedur,
                         color = factor(subj)))+
    facet_wrap(~factor(condition))+
  labs(title = 'Smallt Data')


ggplot()+geom_smooth(data=pilotdata,
                     aes(x = trial,
                         y = movedur,
                         color = factor(subj)))+
    facet_wrap(~factor(condition))+
  labs(title = 'No Target')

```

## Grouped 

```{r}
ggplot()+geom_smooth(data=prefdata,
                     aes(x = trial,
                         y = movedur))+
    facet_wrap(~factor(condition))+
  labs(title = 'Preferred')


ggplot()+geom_smooth(data=smalltdata,
                     aes(x = trial,
                         y = movedur))+
    facet_wrap(~factor(condition))+
  labs(title = 'Smallt Data')


ggplot()+geom_smooth(data=pilotdata,
                     aes(x = trial,
                         y = movedur))+
    facet_wrap(~factor(condition))+
  labs(title = 'No Target')

```

# Peak Vel

## Split by subj

```{r}
ggplot()+geom_smooth(data=prefdata,
                     aes(x = trial,
                         y = peakvel_target,
                         color = factor(subj)))+
    facet_wrap(~factor(condition))+
  labs(title = 'Preferred')


ggplot()+geom_smooth(data=smalltdata,
                     aes(x = trial,
                         y = peakvel_target,
                         color = factor(subj)))+
    facet_wrap(~factor(condition))+
  labs(title = 'Smallt Data')


ggplot()+geom_smooth(data=pilotdata,
                     aes(x = trial,
                         y = peakvel_target,
                         color = factor(subj)))+
    facet_wrap(~factor(condition))+
  labs(title = 'No Target')

```

## Grouped 

```{r}
ggplot()+geom_smooth(data=prefdata,
                     aes(x = trial,
                         y = peakvel_target))+
    facet_wrap(~factor(condition))+
  labs(title = 'Preferred')


ggplot()+geom_smooth(data=smalltdata,
                     aes(x = trial,
                         y = peakvel_target))+
    facet_wrap(~factor(condition))+
  labs(title = 'Smallt Data')


ggplot()+geom_smooth(data=pilotdata,
                     aes(x = trial,
                         y = peakvel_target))+
    facet_wrap(~factor(condition))+
  labs(title = 'No Target')

```